const themes = [
    { name: 'light', value: 'light' },
    { name: 'dark', value: 'dark' },
    { name: 'cupcake', value: 'cupcake' },
    { name: 'forest', value: 'forest' },
    { name: 'garden', value: 'garden' },
    { name: 'halloween', value: 'halloween' },
    { name: 'valentine', value: 'valentine' },
    { name: 'cyberpunk', value: 'cyberpunk' },
    { name: 'synthwave', value: 'synthwave' },
    { name: 'retro', value: 'retro' },
    { name: 'corporate', value: 'corporate' },
    { name: 'emerald', value: 'emerald' },
    { name: 'bumblebee', value: 'bumblebee' },
    { name: 'night', value: 'night' },
    { name: 'lemonade', value: 'lemonade' },
    { name: 'acid', value: 'acid' },
    { name: 'business', value: 'business' },
    { name: 'autumn', value: 'autumn' },
    { name: 'cmyk', value: 'cmyk' },
    { name: 'dracula', value: 'dracula' },
    { name: 'luxury', value: 'luxury' },
    { name: 'black', value: 'black' },
    { name: 'wireframe', value: 'wireframe' },
    { name: 'fantasy', value: 'fantasy' },
    { name: 'pastel', value: 'pastel' },
    { name: 'lofi', value: 'lofi' },
    { name: 'aqua', value: 'aqua' },
    { name: 'winter', value: 'winter' },
    { name: 'coffee', value: 'coffee' },
  ]

  export default themes